apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-magrib
spec:
  selector:
    matchLabels:
      app: pokemagrib
  template:
    metadata:
      labels:
        app: pokemagrib
    spec:
      containers:
      - name: pokemagrib
        image: maulanabn/miniproject:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001                           
        # livenessProbe:                            
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
      # imagePullSecrets:
      #   - name: melissa-hol-group
---
apiVersion: v1
kind: Service
metadata:
  name: pokemagrib-svc
spec:
  selector:
    app: pokemagrib
  ports:
  - port: 80
    targetPort: 5001