apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maulanabn-miniproject
bases:
  - "nginx.yaml" 
resources:
  - "../../service/config/overlays/develop"
  - "../../service/pokecanov/overlays/develop"