apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokemagrib-ingress
spec:
  rules:
  - host: pokemagrib.shamirhusein.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pokemagrib-svc  
            port: 
              number: 80
  ingressClassName: nginx